### ISSUE TITLE
Native/non-engine energy evaluations

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-interchange#279]
For some machine learning frameworks, I think evaluating the objective function is a key performance bottleneck. As of now, the only way to get energy evaluations is to delegate out to an engine (`.to_openmm()` / `.to_top()` etc.). This isn't likely to be a bottleneck in typical MD workflows as it only happens once or a small number of times. But  training on several thousand iterations would probably not be tractable if those conversions needed to happen tens of thousands of times. This may motivate other energy evaluation methods that don't rely on exporting to an MD engine. This could be calling out to NumPy or building on top of existing project (maybe OpenMM's PyTorch  plugin or TorchMD?).

At some level, this is obviously duplicated effort. I'm not excited about the idea of re-writing an MD engine, but I think that most of the headaches (integrators, pressure/temperature control, etc.) would be out of scope here. We'd just want to get the energy from a single configuration, given the complete positions, physics, connectivity, etc.

Feel free to correct any assumptions I've made; I have not dug deeply enough into machine learning infrastructure to think of the best way to approach this.

cc: @SimonBoothroyd @mrshirts @jchodera

**Comment by mattwthompson** [comment]
Another tool: https://software.acellera.com/docs/latest/htmd/tutorials/FFEvaluate.html

**Comment by SimonBoothroyd** [comment]
I have a proof of concept package for doing this that is currently based on `pytorch` [called `smirnoffee`](https://github.com/SimonBoothroyd/smirnoffee). I mainly built this as a mechanism for giving feedback on `interchange` and especially the 'vectorisation' of SMIRNOFF force fields and interchange objects, and for playing around with a `pytorch` based `forcebalance` replacement that may be useful.

`torchmd` looks interesting but seems pretty integrated with the Acellera stack which is licensed under an Acellera specific license that is non-comerical IIRC, and also seems to not have had many updates for a while so I'm not sure the status of it.

> but I think that most of the headaches (integrators, pressure/temperature control, etc.) would be out of scope here

Agreed - if we want a full blown engine we should probably just use `timemachine`.

**Comment by mrshirts** [comment]
I agree that for the near future, it should be limited to only single-point energy evaluations.  Forces should only be calculated by autodifferentiation, not coded.  I also would suggest to no periodic boundary conditions or modifications of the long-range interactions, so that they are all infinite. That simplifies the scope drastically; Coulomb's law is now one line without any simulation-specific parameters (no PME, etc).  If one is optimizing on **molecules**, rather than **systems**, that should be sufficient.

**Comment by jchodera** [comment]
> torchmd looks interesting but seems pretty integrated with the Acellera stack which is licensed under an Acellera specific license that is non-comerical IIRC, and also seems to not have had many updates for a while so I'm not sure the status of it.

I'm not sure which repo you're looking at, but [TorchMD](https://github.com/torchmd/torchmd) is licensed under the permissive [MIT License](https://github.com/torchmd/torchmd/blob/master/LICENSE.md) and will be partially supported for several years via the OpenMM NIH R01.

[espaloma](https://github.com/choderalab/espaloma) is another possibility, with a DGL-based implementation that has an interface to multiple ML framework backends. It's still young, but reasonably well-architected, and may be useful to integrate because it also has extremely useful parameter-assignment capabilities.

[timemachine](https://github.com/proteneer/timemachine) is focused on performance and learning based on free energies. This could be extremely useful if we wanted to pool resources on a complete forcebalance replacement, but also means it has a lot of complex moving parts and custom kernels that would require pooling resources to support. It's certainly worth a discussion, though!

**Comment by mattwthompson** [comment]
IANAL. I think the problem with TorchMD is that it [depends](https://github.com/torchmd/torchmd/blob/3e12a6858c603af6c2b76696ff4edf0956dc0ea5/requirements.txt#L3)  on `moleculekit` which has a [license](https://github.com/Acellera/moleculekit/blob/master/LICENSE) that has different terms than MIT.

At a [quick glance](https://github.com/torchmd/torchmd/search?q=moleculekit), however, it looks like it only uses a single class (a molecule object) and might not be to deeply interwoven into the codebase; I wonder if it would be possible to swap it out for a different representation, like ours or one that's more lightweight.

**Comment by mattwthompson** [comment]
This has been de-prioritized and is underspecified, but we can pick this up again if there is interest.

There doesn't seem to be any changes to TorchMD's licensing, which is a barrier for adopting it here.
