### ISSUE TITLE
Little-endian not enforced

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-interchange#345]
https://github.com/openforcefield/openff-interchange/blob/a19ec32c65c9057a9c0ce81cc1a42931e6ea7ae4/openff/interchange/types.py#L204-L206

`newbyteorder` is not side-effecting so this doesn't really do anything. You may want

```
dt = np.dtype(int).newbyteorder("<") 
```

This does look difficult to test on normal architectures.

```pycon
>>> dt = np.dtype(int)
>>> dt.byteorder
'='
>>> dt.newbyteorder("<")
dtype('<i8')
>>> dt.byteorder
'='
```

**Comment by mattwthompson** [comment]
This is what happens when I copy code when I don't grok - thanks for catching.

I think this originates in similar code in the toolkit - actually the same thing (bug/misbehavior) [still exists there](https://github.com/openforcefield/openff-toolkit/blob/9a9289cef2e7114be92201abfab318959c8bca33/openff/toolkit/utils/utils.py#L693-L694). So ... maybe neither package enforces little endian ... and no resulting problems have cropped up? Again, I don't recall its importance here, so this all only adds to my confusion.

It does seem like this should be patched as you recommend, but maybe `dt.newbyteorder("<")` should just be dropped?

**Comment by lilyminium** [comment]
It seems like a good idea to enforce endianness in case you swap between architectures where the native order differs. It does affect the order that the bytes are interpreted in, so having a protocol for serialisation is usually recommended for safety; possibly problems haven't cropped up yet because users just haven't really switched serialized data between, say, PowerPC (big-endian) and x86 (little-endian). The bit I linked is for deserialization/interpretation though, I suppose it's a little pointless if the serialization doesn't also enforce endianness. Numpy has a little note on this here: https://numpy.org/doc/stable/reference/generated/numpy.frombuffer.html
