### ISSUE TITLE
SMIRNOFF handlers don't inherit `BaseXXXHandler` classes

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-interchange#366]
## Description

I just wanted to clarify what the goal of the `BaseXXXHandler` classes are? It seems like a good idea to have base classes for common handler types, but it seems these aren't used by the `SMIRNOFFXXXHandler` classes. Is the plan that only some handlers will inherit from them, or is this just an accidental omission?

**Comment by SimonBoothroyd** [comment]
If these are base classes they should also probably inherit `abc.ABC` as well.

**Comment by mattwthompson** [comment]
The handlers in `openff.interchange.components.base` were made when I was working on the Intermol conversion layer when I needed something more specific than `PotentialHandler` but with most of the SMIRNOFF-specific details stripped out. There is some overlap; I could see them being removed in the future or everything reconfigured so that the SMIRNOFF handlers inherit from them.
