### ISSUE TITLE
Make `openff.interchange.interop.internal` private

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-interchange#369]
## Description

If `openff.interchange.interop.internal` should be a private / internal submodule you may want to consider making that clear by affixing an underscore so the name becomes `openff.interchange.interop._internal`

**Comment by SimonBoothroyd** [comment]
Same with `openff.interchange.interop.external` - is the user ever expected to do:

```
from openff.interchange.interop.external import XXX
```

**Comment by mattwthompson** [comment]
These modules got their name not because of the intent of their audience but whether or not the interoperability grit happens with custom code (internal) or via exporting to another module (externnal) that does the heavy lifting. I grant these names are not optimal, that they should be shuffled around in some way, and likely not live in the public API long-term.

**Comment by mattwthompson** [comment]
This module no longer exists and its submodules have been replaced by by slightly shorter import paths


```
from openff.interchange.interop.openmm import ...
```
