### ISSUE TITLE
Slow energy minimization on OpenMM system created from Interchange

### ISSUE THREAD

**Issue by ziyuanzhao2000** [openforcefield/openff-interchange#550]
As mentioned in another [issue](1446) over there at the OpenFF Toolkit issue tracker,  I'm currently writing a tool based upon OpenFF's API for modifying chemical structures (will work for proteins, for sure). A function I've implemented is to procedurally grow functional groups on the existing structure. I hope to do a local energy minimization after every such modification, but as of now using OpenMM seems pretty slow relative to, say, similar minimization functionality provided by softwares like openbabel and MOE.

So I'm now looking into why I'm getting this apparent slowdown. In my original workflow, I built my code for manipulate chemical structures atop OpenFF's API, so the natural choice was to first create an Interchange object with the Sage forcefield, which should be proper for small molecules, and then I export the system and topology to OpenMM. I then compared this to using [openmmforcefields](https://github.com/openmm/openmmforcefields) (yeah, slightly confusing names...), where I passed in the SMILES code to perform AM1-BCC charge assignment and generation of GAFF parameters on the fly. Then I use OpenMM to build my system directly. Both procedure gives me very close structures for small molecules after energy minimization in OpenMM. Surprisingly, the latter approach without Interchange/OpenFF is much faster. And this issue is opened to investigate the reason.

Below I demonstrate a minimal working example.

I start with a dipeptide ACE-ALA, which is included in the OpenFF test suite. I take the conformers generated from Rdkit and use MOE to modify the dihedral angles to introduce steric clash:

![Screen Shot 2022-10-31 at 5 43 40 PM](https://user-images.githubusercontent.com/78766247/199116165-99431dcb-fd2b-4a9c-85a9-0018f4fd1a1d.png)

Starting structure in PDB and SDF formats: [dipeptide_clashing.zip](https://github.com/openforcefield/openff-interchange/files/9905216/dipeptide_clashing.zip)

As shown in the figure above, very offending 1,3-interactions, and the expectation is that energy minimization should resolve this bad starting structure.

**Comment by ziyuanzhao2000** [comment]
Firstly, I show the code for using openmmforcefields to minimize this structure and the running time:

```
# AM!-BCC + GAFF using OpenMMforcefields

# Create an OpenFF Molecule object for benzene from SMILES
from openff.toolkit.topology import Molecule
dipeptide_smiles = '[H][N]([C](=[O])[C]([H])([H])[H])[C@]([H])([C](=[O])[O-])[C]([H])([H])[H]'
molecule = Molecule.from_smiles(dipeptide_smiles)

# Create the GAFF template generator
from openmmforcefields.generators import GAFFTemplateGenerator
gaff = GAFFTemplateGenerator(molecules=molecule)

# Create an OpenMM ForceField object with AMBER ff14SB and TIP3P with compatible ions
from openmm.app import ForceField
forcefield = ForceField()
forcefield.registerTemplateGenerator(gaff.generator)


# You can now parameterize an OpenMM Topology object that contains the specified molecule.
# forcefield will load the appropriate GAFF parameters when needed, and antechamber
# will be used to generate small molecule parameters on the fly.
from openmm.app import PDBFile
pdbfile = PDBFile('dipeptide_clashing.pdb')

# Extract the topology and coordinates from the PDB file and then build a system
# with the GAFF parametrized forcefield
import numpy as np
import simtk.unit as openmm_unit 
molecule_top = pdbfile.topology
molecule_pos = pdbfile.positions
molecule_top.setPeriodicBoxVectors(np.eye(3)*100*openmm_unit.angstrom)
molecule_system = forcefield.createSystem(molecule_top)

# Prepare the simulation using the standard setup
from simtk.openmm import LangevinMiddleIntegrator
from simtk.openmm.app import Simulation
integrator = LangevinMiddleIntegrator(298.15*openmm_unit.kelvin, 1/openmm_unit.picosecond, 
                                      0.002*openmm_unit.picoseconds)
simulation = Simulation(molecule_top, molecule_system, integrator)
simulation.context.setPositions(molecule_pos)
```

And then in the next cell, we time the energy minimization call
```
%%time
simulation.minimizeEnergy()
```
> CPU times: user 171 ms, sys: 134 ms, total: 305 ms
> Wall time: 468 ms

is what I see on my Macbook M1 Pro from 2021, using CPU only.

**Comment by ziyuanzhao2000** [comment]
Next, I show the code and results when I use OpenFF Interchange
```
from openff.toolkit import ForceField as OpenFF_ForceField
from openff.units import unit as OpenFF_unit
from openff.interchange import Interchange

# Use OpenFF to import the PDB file by providing smiles code, load Sage forcefield, and define the box
mol = Molecule.from_file('dipeptide_clashing.sdf', 'sdf')
sage = OpenFF_ForceField("openff-2.0.0.offxml")
cubic_box = (
    np.array(
        [
            [100.0, 0.0, 0.0],
            [0.0, 100.0, 0.0],
            [0.0, 0.0, 100.0],
        ]
    )
    * OpenFF_unit.angstrom
)

# Build the Interchange object and export to OpenMM system and topology for simulation
interchange = Interchange.from_smirnoff(topology=[mol], force_field=sage, box=cubic_box) # Is this equivalent to using `create_interchange`?
openmm_sys = interchange.to_openmm() 
openmm_top = interchange.topology.to_openmm()

# Prepare the simulation using the standard setup as before, but with different OpenMM system and topology objects
integrator = LangevinMiddleIntegrator(298.15*openmm_unit.kelvin, 1/openmm_unit.picosecond, 
                                      0.002*openmm_unit.picoseconds)
simulation = Simulation(openmm_top, openmm_sys, integrator)
assert(np.allclose(np.array(molecule_pos._value),            # check that we use the same coordinates, no unit problems or whatever
                   interchange.topology.get_positions().m))
simulation.context.setPositions(molecule_pos)
```
and then take the time again.
```
%%time
simulation.minimizeEnergy()
```

But this time it's much slower! 
>CPU times: user 434 ms, sys: 277 ms, total: 710 ms
>Wall time: 2min 10s

**Comment by ziyuanzhao2000** [comment]
Finally, I visually compared the two minimized structures obtained with different procedures. They are pretty close and look normal to me.

![Screen Shot 2022-10-31 at 5 51 59 PM](https://user-images.githubusercontent.com/78766247/199117329-37588b29-dd96-4fd4-8a87-747c607e6ea0.png)


Hence, my questions are:

1. Please help check if my steps above are legit and controlled for as many variables as possible.
2. Is the difference in running time due to that I'm using GAFF vs. SAGE in the two procedures?
3. Or perhaps is the difference due to some significant overhead accessing simulation system data during energy minimization that I can't quite see? Could it be related to OpenFF Interchange's code?

I will mention our experts to check out this issue above and facilitate the discussion:
@Yoshanuikabundi @mattwthompson @j-wags

**Comment by Yoshanuikabundi** [comment]
I can reproduce on Interchange 0.2.2, OpenMM 7.7.0, both with @ziyuanzhao2000's code and with my own:
![gaff_vs_sage](https://user-images.githubusercontent.com/28590748/199152934-80e4b219-aca7-4243-8375-b999918bbe78.png)

Note that actual MD simulation steps are much slower with Sage, even when other inputs are identical.

Notebook here: 
[gaff_vs_sage.zip](https://github.com/openforcefield/openff-interchange/files/9906538/gaff_vs_sage.zip)

**Comment by mattwthompson** [comment]
Thanks for the detailed reproduction - there are a few possible reasons why the generated `System` objects might perform slightly differently but nothing should result in differences on this order of magnitude. This is difficult to diagnose in part because of the sheer number of moving parts - 

1. GAFF and Sage are conceptually similar force fields but differ in some details that have a remote chance of affecting performance, like the use of a [switching function](https://openforcefield.github.io/standards/standards/smirnoff/#vdw) or underspecified implementation details like the Ewald error tolerance
2. Using a general force field to find minimized structures for peptides, even small ones, is not ideal
3. Energy minimization in general is a squirrelly process for MM engine and not one that's designed to promote significant conformational changes in molecules or really driving torsions between states
4. OpenMM's default error tolerance in energy minimization might be too large or too small for this application - too large and it bails out early, too small and it wastes coal making changes that are too small to be important
5. OpenMM's CPU platform is not great, but some parts of it [should be improved in the upcoming Version 8 release](https://github.com/openmm/openmm/releases/tag/8.0.0beta)

**Comment by mattwthompson** [comment]
The first thing I did was serialize out the systems:

```python3
from openmm import XmlSerializer

with open('gaff_system.xml', 'w') as f1:
    f1.write(XmlSerializer.serialize(gaff_system))

with open('sage_system.xml', 'w') as f2:
    f2.write(XmlSerializer.serialize(sage_system))
```

Then I poked around in the files a little. One thing I found was the default Ewald error tolerance differs by what I always thought was not clearly important

```
grep -r alpha gaff_system.xml sage_system.xml                                                                                                                                          9:39:39
gaff_system.xml:		<Force alpha="0" cutoff="1" dispersionCorrection="1" ewaldTolerance=".0005" exceptionsUsePeriodic="0" forceGroup="0" includeDirectSpace="1" ljAlpha="0" ljnx="0" ljny="0" ljnz="0" method="0" name="NonbondedForce" nx="0" ny="0" nz="0" recipForceGroup="-1" rfDielectric="78.3" switchingDistance="-1" type="NonbondedForce" useSwitchingFunction="0" version="4">
sage_system.xml:		<Force alpha="0" cutoff=".9" dispersionCorrection="1" ewaldTolerance=".0001" exceptionsUsePeriodic="0" forceGroup="0" includeDirectSpace="1" ljAlpha="0" ljnx="0" ljny="0" ljnz="0" method="4" name="NonbondedForce" nx="0" ny="0" nz="0" recipForceGroup="-1" rfDielectric="78.3" switchingDistance="-1" type="NonbondedForce" useSwitchingFunction="0" version="4">
```

Hacking around with this:

```python3
# Prepare system with Sage
sage_system = interchange.to_openmm(combine_nonbonded_forces=True)

for force in sage_system.getForces():
    if isinstance(force, openmm.NonbondedForce):
        force.setEwaldErrorTolerance(0.0001)
        break

# Prepare simulation
sage_simulation = openmm.app.Simulation(top_from_pdb, sage_system, deepcopy(integrator))
sage_simulation.context.setPositions(positions_from_pdb)
```

Gives these timings:
```python3
%%time
sage_simulation.minimizeEnergy()

# Wall time for this cell based on the value passed to force.setEwaldErrorTolerance()
# times: Dict[float, float] = {0.1: 2.3, 0.01:, 3.93, 0.001: 20.8, 0.0005: 34.3, 0.0001: 136}
```
This doesn't close the gap, but it does indicate that
* effectively turning off the PME calculations (0.1) knocks off most of the runtime
* the difference between 0.0005 and 0.0001, at least using the CPU platform on my machine, has a huge impact (which might go away with OpenMM 8)

![image](https://user-images.githubusercontent.com/7935382/199260757-f5cc2d86-2d81-47cb-964c-85047f02ec2f.png)

**Comment by mattwthompson** [comment]
To try to reduce the number of moving parts, I made a system with Sage via `openmmforcefields`:

```python3
# Prepare system with Sage via openmmforcefields
_sage_template = SMIRNOFFTemplateGenerator(molecules=molecule)
_sage = openmm.app.ForceField()
_sage.registerTemplateGenerator(_sage_template.generator)

_sage_system = _sage.createSystem(top_from_pdb)

# Prepare simulation
_sage_simulation = openmm.app.Simulation(top_from_pdb, _sage_system, deepcopy(integrator))
_sage_simulation.context.setPositions(positions_from_pdb)
```

If Interchange is making an error, we'd expect this to be fast. If there's some hidden difference in the force fields, this will be slow.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/7935382/199262027-a64f3322-857c-40cc-9a22-9893aa11bd5f.png">


It's fast, so something with the pure OpenFF pathway is introducing a slowdown.

Serializing these indicates the notable difference that `openmmforcefields` uses the _unconstrained_ version of Sage but the original code here uses the version with constraints. This doesn't end up making a difference but is something to consider in your work.

```
for system in [gaff_system, sage_system, _sage_system]:
    print(system.getNumConstraints())
# 0
# 8
# 0
```

**Comment by ziyuanzhao2000** [comment]
Thanks to Matt and Josh for testing this out! 
So to summarize, Matt have eliminated some moving parts that I have overlooked:
0. Set `combine_nonbonded_forces = True` always. 
1. Different Ewald error tolerance, GAFF has 0.0005 but SAGE has stricter tolerance of 0.0001, and this accounts for some of the timing difference.
2. Number of constraints for SAGE as in `openmmforcefields` vs. OpenFF, but this doesn't accounts for the timing difference I observed, because `openmmforcefields` runs about as fast with SAGE or with GAFF.
3. Switching function in nonbonded forces as `openmmforcefields` does not use it, but this still doesn't explain the slowdown.

Please let me know if I misunderstand any step above. 

So it seems that although I can turn off PME to speed things up, we still haven't figured out what is it with OpenFF that causes the slowdown. Let me know if you have any further thoughts or discoveries.

**Comment by Yoshanuikabundi** [comment]
I wonder if there's some undocumented weirdness around how the forces are stored in the system. I can imagine that any MD engine would be optimized around having few atom types that re-use parameters, and having an atom type per atom might have cache locality issues? So maybe the order that forces are added matters or something? Though this seems very unlikely to affect such a small system.

**Comment by Yoshanuikabundi** [comment]
@ziyuanzhao2000 Turning off PME will mean you're technically not using Sage anymore, as we specify that as part of the force field - but it probably doesn't matter too much for energy minimisations. If you do want to use Sage while we track down this apparent bug, you might be able to use the `openmmforcefields.generators.SMIRNOFFTemplateGenerator` class as Matt did above :)

**Comment by mattwthompson** [comment]
I am nudging us toward the possibility that there is not a functional difference in the `openmm.System` objects. The actual content of each is so close to identical that I have a hard time believing that's the root issue.

```shell
$ python -m pip install git+https://github.com/openforcefield/interchange-regression-testing.git
$ mamba install deepdiff rich click -c conda-forge -yq
```

```python3
>>> from pathlib import Path
>>> from deepdiff import DeepDiff
>>> from interchange_regression_utilities.parsing.openmm import load_openmm_system_as_dict
>>>
>>> system1 = load_openmm_system_as_dict(Path("_sage_system.xml.txt"))
>>> system2 = load_openmm_system_as_dict(Path("sage_system.xml.txt"))
>>>
>>> DeepDiff(system1, system2, ignore_order=True, significant_digits=6)
{'type_changes': {"root['Forces'][3]['switchingDistance']": {'old_type': <class 'int'>, 'new_type': <class 'float'>, 'old_value': -1, 'new_value': 0.8}}, 'values_changed': {"root['Forces'][3]['method']": {'new_value': 4, 'old_value': 0}, "root['Forces'][3]['Exceptions'][60]['q']": {'new_value': -0.17900855642338528, 'old_value': -0.17900848482712306}}, 'iterable_item_removed': {"root['Forces'][0]": {'forceGroup': 0, 'frequency': 1, 'name': 'CMMotionRemover', 'type': 'CMMotionRemover', 'version': 1}}}
```

The switching distance doesn't matter (`useSwitchingFunction="0"` in both files) and the center of mass motion remover shouldn't be doing anything here

> This class prevents the center of mass of a System from drifting. At each time step, it calculates the center of mass momentum, then adjusts the individual particle velocities to make it zero.

**Comment by mattwthompson** [comment]
I can't explain why, but the differences are smaller if using the CPU platform. By default it's using OpenCL, no matter what Apple has to say on the matter. My code has not changed much from before; I believe the only relevant change is like so:

```python3
# Prepare simulation
sage_simulation = openmm.app.Simulation(
    ...
    platform=openmm.Platform.getPlatformByName("CPU"),
)
```
And the same for `_sage_simulation`.

<img width="588" alt="image" src="https://user-images.githubusercontent.com/7935382/199517513-559e080a-1641-4150-98ea-1bd453986663.png">

<img width="583" alt="image" src="https://user-images.githubusercontent.com/7935382/199517585-838206f9-716a-4c3a-a669-6ff51b749133.png">

There's now a factor 6 or so difference, which is not ideal but I'd argue not consequential. If there are significant differences on the CUDA platform, that would be more concerning.

**Comment by mattwthompson** [comment]
My notebook now gives similar (slightly better, actually) timings for the pure OpenFF pathway compared to the route through `openmmforcefields`.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/7935382/199542513-7e0bc5a9-154e-40cb-b6b6-9bd94323b869.png">

I'm not sure why; I have some good leads but I was not able to reproduce any. I'm attaching the most recent version of my notebook with most debug code removed. It shows minimization times of about 20 ms for both code paths and about 1.2s simulation time for 10,000 steps.

Here are some details I experimented with:

* Reducing the box size from 10 nm to 1 nm
* Forcing the `openmmforcefields`-generated pathway to use PME
* Using and not using a periodic box at all
* Messing with the Ewald tolerance in the Interchange pathway again
* Starting the Sage systems with the positions from minimizing with GAFF
* Removing the `openmm.CMMotionRemover` force from the systems generated by `openmmforcefields`
* OpenMM 7 vs. 8 - no significant difference, only tested accidentally
* Using each of the three platforms available on my machine

I can elaborate further on any of these if they look promising. Each had subtleties and some led to some performance changes, but none cause differences on the order of a hundred or so.

I'm just attaching the notebook I have up now. [This](https://gist.github.com/mattwthompson/bfd6e72a1ba341c8972aea9422ac5f2c) I have up right now. Please have a look through it and see if anything stands out to you. I could easily be forgetting something since I'm not keeping a good paper trail.

[issue-550.ipynb.txt](https://github.com/openforcefield/openff-interchange/files/9922221/issue-550.ipynb.txt)

**Comment by ziyuanzhao2000** [comment]
Hi Matt and Josh, thanks for your continued attention to this issue!

I've just checked out Matt's latest notebook, which summarized the different pathways we discussed above. Right now I feel the second one is most immediately adaptable to my current need, i.e., I just fall back to `openmmforcefields` to use the Sage forcefield.

However, I'm still confused why for the Sage + pure OpenMM pathway (the third), I could not reproduce what Matt saw, that it can do energy minimization as fast as with the first two pathways. In my case, if I load `_sage_system.xml.txt` for the third pathway, I get a very slow result as shown below:

<img width="983" alt="Screen Shot 2022-11-02 at 12 53 47 PM" src="https://user-images.githubusercontent.com/78766247/199552253-e06519b5-d375-498f-93d6-48dda96f1561.png">

And most perplexingly, if I don't load the system from xml file but just relied on the initialization from this code block in Matt's notebook:

```
%%time
# Prepare system with Sage
sage_system = interchange.to_openmm(combine_nonbonded_forces=True)

update_ewald = False

for force in sage_system.getForces():
    if update_ewald and isinstance(force, openmm.NonbondedForce):
        force.setEwaldErrorTolerance(0.0005)
        break

# Prepare simulation
sage_simulation = openmm.app.Simulation(
    topology=interchange.to_openmm_topology(),
    #system=XmlSerializer.deserialize(open("sage_system.xml").read()),
    system=sage_system,   # *** use what we just initialized above ***
    integrator=LangevinMiddleIntegrator(
        298.15 * openmm.unit.kelvin,
        1 / openmm.unit.picosecond,
        0.002 * openmm.unit.picoseconds,
    ),
    platform=openmm.Platform.getPlatformByName("Reference"),
)
sage_simulation.context.setPositions(ensure_quantity(interchange.positions, "openmm"))
```

Then the energy minimization call just hang on my computer... I believe I have similar system specs as Matt's macbook so I'm not sure why I have this problem.

Please kindly advise how can I get good performance with OpenFF Interchange, or I'm afraid I will have to use `openmmforcefields` for now.

**Comment by mattwthompson** [comment]
Use a smaller box, or none at all. The issue is that computing PME electrostatics is poorly-suited for a single molecule in a large box, which is implemented much more differently than not using any box at all. Run this script to see what happens when the box is `None` or slowly increased from 20 Angstroms:

```python3
import time
from copy import deepcopy

import numpy
import openmm.app
import openmm.unit
from openff.interchange import Interchange
from openff.toolkit import ForceField, Molecule
from openff.units import unit
from openff.units.openmm import ensure_quantity
from openmm import LangevinMiddleIntegrator

molecule = Molecule.from_file("dipeptide_clashing.sdf", "sdf")
pdbfile = openmm.app.PDBFile("dipeptide_clashing.pdb")

for box in [None, *numpy.linspace(20, 100, 20, dtype=int)]:
    print(f"Building system with box length {box}")

    if box is not None:
        box = numpy.eye(3) * box * openmm.unit.angstrom

    integrator = LangevinMiddleIntegrator(
        298.15 * openmm.unit.kelvin,
        1 / openmm.unit.picosecond,
        0.002 * openmm.unit.picoseconds,
    )

    sage = ForceField("openff_unconstrained-2.0.0.offxml")

    interchange = Interchange.from_smirnoff(
        topology=[molecule], force_field=sage, box=box
    )

    sage_system = interchange.to_openmm(combine_nonbonded_forces=True)

    openmm_topology = topology = interchange.to_openmm_topology()

    if box is not None:
        openmm_topology.setPeriodicBoxVectors(ensure_quantity(box, "openmm"))

    sage_simulation = openmm.app.Simulation(
        topology=openmm_topology,
        system=sage_system,
        integrator=deepcopy(integrator),
        platform=openmm.Platform.getPlatformByName("Reference"),
    )

    sage_simulation.context.setPositions(
        ensure_quantity(interchange.positions, "openmm")
    )

    if box is not None:
        sage_simulation.context.setPeriodicBoxVectors(
            *openmm_topology.getPeriodicBoxVectors()
        )

        state = sage_simulation.context.getState()
        numpy.testing.assert_allclose(
            state.getPeriodicBoxVectors(asNumpy=True),
            interchange.box.m_as(unit.nanometer),
        )

    now = time.time()
    print("Minimizing ...")
    sage_simulation.minimizeEnergy()
    print(f"\t... complete! Took {time.time() - now}")
```

I didn't wait for it to complete, since it's clear that the scaling is poor with a few nanometers of vacuum padding on either side of the molecule:

```shell
(openff-interchange-env) [gaff_vs_sage] python sage_box.py                                       13:31:30
Building system with box length None
Minimizing ...
	... complete! Took 0.003755807876586914
Building system with box length 20
Minimizing ...
	... complete! Took 0.2906229496002197
Building system with box length 24
Minimizing ...
	... complete! Took 0.5698928833007812
Building system with box length 28
Minimizing ...
	... complete! Took 1.0410590171813965
Building system with box length 32
Minimizing ...
	... complete! Took 1.5461950302124023
Building system with box length 36
Minimizing ...
	... complete! Took 1.3439888954162598
Building system with box length 41
Minimizing ...
	... complete! Took 2.3016598224639893
Building system with box length 45
Minimizing ...
	... complete! Took 10.957913875579834
Building system with box length 49
Minimizing ...
	... complete! Took 39.92921495437622
Building system with box length 53
Minimizing ...
	... complete! Took 56.052218198776245
Building system with box length 57
Minimizing ...
^C^C^C^C^C^C^CTraceback (most recent call last):
  File "/Users/mattthompson/Downloads/gaff_vs_sage/sage_box.py", line 65, in <module>
    sage_simulation.minimizeEnergy()
  File "/Users/mattthompson/mambaforge/envs/openff-interchange-env/lib/python3.9/site-packages/openmm/app/simulation.py", line 137, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations)
  File "/Users/mattthompson/mambaforge/envs/openff-interchange-env/lib/python3.9/site-packages/openmm/openmm.py", line 12538, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
KeyboardInterrupt
```

Since this `Interchange` is constructed with a box, it considers the system to be periodic and Sage uses PME electrostatics for periodic systems. These can be constructed with `box=None` to coax OpenMM to use `NoCutoff`:

```
In [13]: Interchange.from_smirnoff(
    ...:     topology=[molecule],
    ...:     force_field=sage,
    ...:     box=unit.Quantity(100 * numpy.eye(3), unit.angstrom),
    ...: ).to_openmm(combine_nonbonded_forces=True).getForce(0).getNonbondedMethod()
Out[13]: 4

In [14]: Interchange.from_smirnoff(topology=[molecule], force_field=sage, box=None).to_openmm(
    ...:     combine_nonbonded_forces=True,
    ...: ).getForce(0).getNonbondedMethod()
Out[14]: 0

In [15]: openmm.NonbondedForce.NoCutoff, openmm.NonbondedForce.PME  # the ints are aliases for these methods
Out[15]: (0, 4)
```
`NoCutoff` was used when you were calling `openmm.app.ForceField`, even though the topology had box vectors. I don't know exactly why that's the case (probably it's assumed they'll be set using the [extra arguments](http://docs.openmm.org/latest/api-python/generated/openmm.app.forcefield.ForceField.html#openmm.app.forcefield.ForceField.createSystem)) but I trust there are good reasons for OpenMM's defaults - and you can see how customizable it is if the defaults are not appropriate.

If your work continues to be focused on individual small molecules or small peptides without solvent, not setting the box is probably fine - PME is generally only appropriate for condensed phase systems.

**Comment by ziyuanzhao2000** [comment]
@mattwthompson That's fair. I did what you suggested and it's indeed faster. For my application I don't really need the periodicity so I'm just going to turn off the box when creating the Interchange.

Though this still doesn't address why using `openmmforcefields` with the box (so with all that PME calculation) is as fast as using Interchange without the box, i.e., why Interchange's OpenMM system is much slower with the box. Please feel free to close this issue once you finished debugging and found the cause, or if you think it's not OpenFF problem after all.

**Comment by mattwthompson** [comment]
The system created by `openmmforcefields` was not using PME calculations. If not passing optional arguments to `ForceField.createSystem`, [OpenMM defaults](http://docs.openmm.org/latest/api-python/generated/openmm.app.forcefield.ForceField.html#openmm.app.forcefield.ForceField.createSystem) to using `NoCutoff`, thereby modifying Sage into something else - applied to periodic systems, [Sage must use PME](https://openforcefield.github.io/standards/standards/smirnoff/#electrostatics). The OpenFF stack maintains[^1] this information, but OpenMM's force field object does not (historically these are not considered a part of a force field definitions).

Even though you set the periodic box on the `Topology` object, and even though the `State` object has box vectors, the `System`  _is not using PME_. (It's reasonable to anticipate it to update that information, but it's also the sort of state management that gets out of control for anything but a couple simple cases, so I see why OpenMM does not do this.) I can demonstrate this using [this](https://gist.github.com/mattwthompson/68805caa33801b177a751f7ce170e419) script and you can `:%s/SMIRNOFF/GAFF/g` to see similar behavior using either force field.

```shell
$ python pme_timing.py
force.getNonbondedMethod()=0
Minimizing, extra_args=False, ...
	... complete! Took 0.003731966018676758
force.getNonbondedMethod()=4
Minimizing, extra_args=True, ...
	... complete! Took 7.951444864273071
```


Since `openmmforcefields` is limited in scope to providing force fields, there's no clear way for it to maintain the information. I'd love to figure out a way to smooth that over, but I think it's just incongruent with those object models. Interchange is a different in that, inspired by SMIRNOFF, it can take this information from force fields and pass it through to exporters, so it does.


[^1]: See `sage['Electrostatics'].periodic_potential` or `interchange['Electrostatics'].periodic_potential` in these notebooks)

**Comment by ziyuanzhao2000** [comment]
Great, thank you for elaborating your points again and the notebook! Now it all makes sense that whether the PME is on or off across the different setups makes the most difference in the runtime for my case.
