### ISSUE TITLE
Comparing the openMM and Gromacs energy

### ISSUE THREAD

**Issue by xiki-tempula** [openforcefield/openff-interchange#552]
**Description**
I'm interested in using openff-interchange. To ensure that I will get the same topology/hamiltonian/energy for both openMM and Gromacs, I have tested a small ligand solvated in TIP3P water. I kind of get an energy difference at the scale of 2 kJ/mol between the openMM energy and Gromacs energy. I wonder if you have done similar energy comparison and have some information about it? Thank you.

**Comment by mattwthompson** [comment]
We've done these sorts of comparisons a lot over the years, including adding a module that tries to make it easy:

https://github.com/openforcefield/openff-interchange/blob/v0.2.2/openff/interchange/drivers/__init__.py#L2-6

Each of these functions has a similar signature: input an `Interchange` and get out an `EnergyReport`, which reports the potential energy function split up into as many terms as the engine reports. These can be dropped in anywhere you have an `Interchange` object constructed (with positions, etc.) and it will run a single-point energy with each engine it can find installed on the machine. For example, using [this](https://github.com/openforcefield/openff-interchange/tree/v0.2.2/examples/ligand_in_water) example, I can pop these lines in after Cell 11:

```python3
from openff.interchange.drivers import get_all_energies

get_all_energies(interchange)
```

and it finds OpenMM, GROMACS, and Amber on my machine:

```
{'OpenMM': EnergyReport(energies={'Bond': <Quantity(5.38659668, 'kilojoule / mole')>, 'Angle': <Quantity(147.566315, 'kilojoule / mole')>, 'Torsion': <Quantity(25.6188812, 'kilojoule / mole')>, 'vdW': <Quantity(143941.605, 'kilojoule / mole')>, 'Electrostatics': <Quantity(230.016704, 'kilojoule / mole')>}),
 'Amber': EnergyReport(energies={'Bond': <Quantity(1.2878, 'kilocalories_per_mole')>, 'Angle': <Quantity(1754.1312, 'kilocalories_per_mole')>, 'Torsion': <Quantity(6.1231, 'kilocalories_per_mole')>, 'vdW': <Quantity(145207.746, 'kilojoule_per_mole')>, 'Electrostatics': <Quantity(-156758.085, 'kilojoule_per_mole')>}),
 'GROMACS': EnergyReport(energies={'Bond': <Quantity(5.38660622, 'kilojoule / mole')>, 'Angle': <Quantity(7305.02529, 'kilojoule / mole')>, 'Torsion': <Quantity(25.6177291, 'kilojoule / mole')>, 'vdW': <Quantity(143941.28, 'kilojoule / mole')>, 'Electrostatics': <Quantity(183.726307, 'kilojoule / mole')>})}
```

In this case the bond, dihedral, and vdW energies compare pretty well. The angle energies are off, but I think this is because the special constraints for water are not yet supported in the GROMACS and Amber exports, but the OpenMM export gets it right. The "constrained" version of sage uses this section:

```
    <Constraints version="0.3">
        <Constraint smirks="[#1:1]-[*:2]" id="c1"></Constraint>
        <Constraint smirks="[#1:1]-[#8X2H2+0:2]-[#1]" id="c-tip3p-H-O" distance="0.9572 * angstrom"></Constraint>
        <Constraint smirks="[#1:1]-[#8X2H2+0]-[#1:2]" id="c-tip3p-H-O-H" distance="1.5139006545247014 * angstrom"></Constraint>
    </Constraints>
```

which constrains h-bonds on the ligand and the bond and angles in water, which is just a case I haven't implemented and tested yet.

The differences in non-bonded energies are a bit more concerning; without spending time digging into it I'd still say with some confidence that the information is being written out to the files accurately but some details get lost between the in-memory and on-disk states. OpenMM allows us to do just about everything we want and keep it in a `Simulation`/`Context` object, but there's more friction converting stuff like constraints and non-bonded settings to Amber and GROMACS files. This is mostly because SMIRNOFF considers these to be a part of the force field (i.e. Sage was trained with a 9 Angstrom cutoff, so that's what it should be used with) and conventional force fields do not.


In general we see good agreement between all engines for valence terms but there is no consensus between engines on how to treat non-bonded terms - what PME settings we can tinker with, what polynomial to use for a switching function, how the vdW cutoff should be treated, ... even the value of the vacuum permittivity varied wildly between engines until Michael Shirts's group took a deep dive into these energy comparisons (https://link.springer.com/article/10.1007/s10822-016-9977-1). It's likely that new and complex systems will report some differences, but the reasons are, in ranked likelihood,

1. Engines differ on a single detail, making tight agreement not feasible
2. One engine does not seem to support a particular feature or setting and I'm forced to do my best to guess at how to approximate this
3. Interchange's `drivers` module silently makes a bad assumption
4. Interchange incorrectly writes out some parameters

If you have a reproducing example that's significantly different from the one I linked above, I'd be happy to dig into it and see if the issue lies in the engines, with Interchange, or at the interface between them.

Lastly, before Interchange was integrated into the toolkit as its interoperability backend, we did [extensive testing](https://github.com/openforcefield/interchange-regression-testing) on a long list of systems to verify that the `openmm.System` generated by Interchange and the "old" toolkit matched to fairly high precision. This included a set of small molecules, some condensed-phase systems, some systems with virtual sites, and some with WBO-interpolated parameters. So at very least we hope that Interchange matches the reference implementation with OpenMM so that we can use that as a reference in improving the exports to other engines.

**Comment by xiki-tempula** [comment]
Many thanks. Looking at your example
```
{'OpenMM': EnergyReport(energies={'Bond': <Quantity(5.38659668, 'kilojoule / mole')>, 'Angle': <Quantity(147.566315, 'kilojoule / mole')>, 'Torsion': <Quantity(25.6188812, 'kilojoule / mole')>, 'vdW': <Quantity(143941.605, 'kilojoule / mole')>, 'Electrostatics': <Quantity(230.016704, 'kilojoule / mole')>}),
 'Amber': EnergyReport(energies={'Bond': <Quantity(1.2878, 'kilocalories_per_mole')>, 'Angle': <Quantity(1754.1312, 'kilocalories_per_mole')>, 'Torsion': <Quantity(6.1231, 'kilocalories_per_mole')>, 'vdW': <Quantity(145207.746, 'kilojoule_per_mole')>, 'Electrostatics': <Quantity(-156758.085, 'kilojoule_per_mole')>}),
 'GROMACS': EnergyReport(energies={'Bond': <Quantity(5.38660622, 'kilojoule / mole')>, 'Angle': <Quantity(7305.02529, 'kilojoule / mole')>, 'Torsion': <Quantity(25.6177291, 'kilojoule / mole')>, 'vdW': <Quantity(143941.28, 'kilojoule / mole')>, 'Electrostatics': <Quantity(183.726307, 'kilojoule / mole')>})}
```
The Electrostatics potential in `OpenMM` is 230.016704 kilojoule / mole while the Electrostatics potential in `Gromacs` is 183.726307 kilojoule / mole. This difference seems to be quite large @wiederm.

**Comment by mattwthompson** [comment]
I looked at this some more. I still think most of the errors are from PME since the charges are the same. OpenMM doesn't implement a hard cutoff for electrostatics, so comparing between engines is difficult. There are some small differences in vdW energies that are similarly difficult to track down.


```python
from openff.evaluator.utils.packmol import pack_box
from openff.toolkit import ForceField, Molecule, Topology
from openff.units import unit
from openff.units.openmm import ensure_quantity

from openff.interchange.components.mdconfig import MDConfig
from openff.interchange.drivers import get_gromacs_energies, get_openmm_energies

sage = ForceField("openff-2.0.0.offxml")

water = Molecule.from_mapped_smiles("[H:2][O:1][H:3]")
ligand = Molecule.from_smiles(
    "CCO"
)  # "C[C@@H]1CC[C@H]2[C@H](C(=O)O[C@H]3[C@@]24[C@H]1CC[C@](O3)(OO4)C)C")
ligand.generate_conformers(n_conformers=1)
ligand.to_file("ligand.pdb", file_format="pdb")

packed_trj, _ = pack_box(
    molecules=[water],
    number_of_copies=[500],
    mass_density=1000.0 * unit.kilogram / unit.meter**3,
    structure_to_solvate="ligand.pdb",
)

packed_topology = Topology.from_openmm(
    openmm_topology=packed_trj.topology.to_openmm(),
    unique_molecules=[water, ligand],
    positions=unit.Quantity(packed_trj.xyz[0], unit.nanometer),
)
packed_topology.box_vectors = unit.Quantity(
    packed_trj.unitcell_vectors[0], unit.nanometer
)

interchange = sage.create_interchange(packed_topology)
interchange["Electrostatics"].cutoff = 0.9 * unit.nanometer
interchange["vdW"].switch_width = 0.0 * unit.nanometer

interchange.to_top("out.top")
interchange.to_gro("out.gro")

mdconfig = MDConfig.from_interchange(interchange)
mdp_file = "tmp.mdp"
mdconfig.write_mdp_file(mdp_file)

print("Openmm: ")
print(
    get_openmm_energies(
        interchange=interchange, combine_nonbonded_forces=False, detailed=True
    )
)

print("GROMACS: ")
print(get_gromacs_energies(interchange))
```
```
Openmm:
Energies:

Bond:          		4.1627808515093285 kilojoule / mole
Angle:         		43.889038813881925 kilojoule / mole
Torsion:       		11.007037031441204 kilojoule / mole
Nonbonded:     		None
vdW:           		12511.949588410764 kilojoule / mole
Electrostatics:		430.3994336354226 kilojoule / mole

GROMACS:
Energies:

Bond:          		4.162807941436768 kilojoule / mole
Angle:         		43.88908767700195 kilojoule / mole
Torsion:       		11.007027626037598 kilojoule / mole
Nonbonded:     		None
vdW:           		12513.34275174141 kilojoule / mole
Electrostatics:		383.1684226989746 kilojoule / mole

**Comment by mattwthompson** [comment]
There isn't much to do here since OpenMM doesn't implement a hard cut-off for electrostatics. Modifying everything to use a `CustomNonbondedForce` with Coulomb's potential hard-coded might be a way to investigate this, but that's getting off of the beaten path. For now I'm comfortable with the parameters being written out identically and relatively at peace with implementation differences in non-bonded energies between engines. It's notoriously difficult to tighten them up.
