### ISSUE TITLE
About the handelling of the over-constrain problem in interchange

### ISSUE THREAD

**Issue by xiki-tempula** [openforcefield/openff-interchange#559]
**Description**
I think one goal of interchange might be that if one generates the small molecule forcefield with openff-toolkit, then use interchange to write it down into a Gromacs topology, reading this topology back into the openMM should give the same topology as just passing the small molecule topology generated by openff-toolkit into openMM.

I have recently encountered an issue with loading the Gromacs topology of methane into openMM and encountered the problem that the over-determined constraint breaks the CCMA constraint solver. https://github.com/openmm/openmm/issues/3856

I wonder if interchange could handle this case correctly. Thanks.

**Comment by mattwthompson** [comment]
I'm curious what handling this case correctly looks like? Interchange cannot modify the behavior of OpenMM or the information content of a GROMACS topology file (which includes no information on constraints). Interchange does not have opinions about which constraint solver should be used.

For using OpenMM and GROMACS, this workflow should produce identical results (modulo the details of how some options are implemented in each engine) with OpenMM and GROMACS, since SMIRNOFF force fields can contain constraint information:


```
 -----------------------------------------------       -------------      ----------------
| SMIRNOFF force field + openff.toolkit.Toplogy |  -> | Interchange | -> | OpenMM objects |
 -----------------------------------------------       -------------      ----------------
                                                             |
                                                             V
                                                      ---------------
                                                     | GROMACS files |
                                                      ---------------
```
Different flows of information are subject to intervention, since i.e. given only GROMACS files it's ambiguous what constraints should be used, if any.
