### ISSUE TITLE
Avoid creating many atomtypes for the same molecules when convert to GROMACS top

### ISSUE THREAD

**Issue by taidbui** [openforcefield/openff-interchange#606]
Hi, 

I created a system of N molecules of the same molecule, then converted the system to gromacs .top file, I found that the .top file contains as N times the atomtypes which is redundant as we only need atomtypes for 1 molecule. Also, in the [ molecules ] section, each molecule type is listed as a separate line when I expect to have one molecule type with N molecules. Below is the code I tried. 
`from openff.toolkit import *
from openff.interchange import *

ethane = Molecule.from_smiles("CC")
ff = ForceField("openff-2.0.0.offxml")
topology = Topology.from_molecules(10 * [ethane])
out = ff.create_interchange(topology)
out.to_top('foo.top')`

- The [ atomtypes ] section: 
![image](https://user-images.githubusercontent.com/28985154/222759850-2fa22aa1-4166-4ecf-8348-3cea0f85876c.png)

- And the [ molecules ] section: 
![image](https://user-images.githubusercontent.com/28985154/222759914-afbd7704-58e7-4f4a-b9bd-00f61cc3317b.png)

I am wondering if there would be a quick fix for this behavior. 

Thanks,

**Comment by j-wags** [comment]
This seems to be another face of the atom type compression problem - Just commenting to link https://github.com/openforcefield/openff-interchange/issues/95#issue-796229052 and https://github.com/openforcefield/openff-toolkit/issues/90 for future indexing.

**Comment by taidbui** [comment]
When convert to Lammps file (we need to have positions), it doesn’t seem to have the same problem though.

**Comment by mattwthompson** [comment]
Thanks for the reproduction - I'm aware of this issue and, believe it or not, it's intentional. This one is tricky and a little more complicated than it initially seems. I understand that printing out each molecule separately makes the files more difficult to inspect, but it's the easiest way to avoid a number of corner cases that would produce incorrect - not simply verbose - files. I'll try to articulate why this looks unappealing and justify why it's actually better than the alternatives.

Jeff's correct to bring in atom type explosion as an issue and it explains why virtually all GROMACS/Amber files of SMIRNOFF systems look comically verbose compared to those prepared with conventional Amber-like force fields. There are a few ways the atom types could be compressed, but file size is extremely cheap and a chance of mis-reporting parameters, no matter how small, is prohibitively expensive, so we have not prioritized this.

A separate issue is how similar molecules are collated into the `[ molecules ]` section. If you're anything like me, you saw those lines of repeated `x0 1` and thought "surely these can be condensed down to 1!" as I did. In your example it certainly looks like they could be. However, defining molecular identity in a way that handles the problem broadly is not straightforward.
* It's non-negotiable that condensing duplicates in `[ molecules ]` must only ever condense two molecules that would produce the same energy given the same coordinates, non-bonded settings, etc.
* Molecule names are borderline arbitrary and not usually provided, and the same goes for residue information, so we can't use that.
* There are some cases in which isomorphic molecules might be assigned different parameters, so the built-in solutions offered by the `Molecule` class probably won't be enough. 
* I could imagine a hashing function that looks into every character of what's written out in a `moleculetype` section and is used for deciding which are equivalent enough to be considered copies of each other. But that's non-trivial to implement and error-prone (any modifications to object models may change the behavior of this function and accidentally introduce a hash collision) so I decided not to implement it the last time I thought about it.

As far as I remember, GROMACS is the only engine that groups molecules up in this specific way, which is another reason why I haven't optimized it. OpenMM doesn't even keep track of molecules in its `System` object, LAMMPS only includes an integer molecule ID in each row of the `Atoms` section, and Amber barely has the concept of molecules at all.

With this context in mind, I hope you understand why it looks a little funny. In the future this may look nicer, but Interchange is not (and may never be) heavily optimized for file size or manual user modification. (If for some reason you want to modify parameters, I imagine doing so via the API instead of by hand or with scripts later.) Are you running into issues with file size?

**Comment by taidbui** [comment]
Thank you for clarification. I got your point now. I had thought initially that it would create N separate topologies for each identical molecule present in the system, which could have been a problem. However, upon further examination, I realize that even though it creates atomtypes for all the atoms in the system, it only creates 3 or 4 moleculetypes that are used to construct the system. Moreover, the atomtypes in each molecule under [ atoms ] section are correctly linked to the atomtypes in the global [ atomtypes ] section. As a result, the redundant atomtypes will not be used and that is fine. And I agreed if we can do a bit of housekeeping to make the final top file looks cleaner that could be perfect. BTW, many thanks for the good work in creating such useful tools.

**Comment by mattwthompson** [comment]
Thanks!

I will also try to document this in a better way.

**Comment by taidbui** [comment]
Hi Matt, 

I got another issue related to this. When I ran a simulation with GROMACS using the converted .gro and .top files, the system just crashed with the following error (on both my computer and a supercomputer):
```
Memory allocation failed:
std::bad_array_new_length

```
I removed the redundant atomtypes (those are not found under the [ atoms ] section in [ moleculetype ]), and the simulation ran just fine. I suspect that the issue is caused by the large number of atom types listed under [atomtypes], which may be causing a high memory load. I wonder if it could be an easy fix by keeping only atomtypes that present under [ moleculetype ] sections instead of listing all the atomtypes based on the number of atoms in the system.

**Comment by mattwthompson** [comment]
I agree with your assessment of the problem and that sounds like a reasonable solution to try. Unfortunately I'm in the middle a huge refactor of that code (#635) so fixing this behavior based on the current state might not make it into a release just based on logistics. Is it possible that manually modifying these files can hold you over for a few weeks? (I'm also assuming that it produces the same results.) After the 0.3.0 release, the next priority is improving GROMACS and then Amber parsers, which should actually come with improvements to those exporters.

Additionally, are you able to share more details of your system? Either general terms (number of atoms, etc.) or specific scripts/files with which I can run tests myself. They can be less interesting (i.e. swapping out another ligand/protein for the ones you're actually studying) since I'm just after performance evaluations.

**Comment by taidbui** [comment]
Hi Matt,
I attached here the system of 10000 ethanol molecules using openff-2.0.0.offxml force field. I ran the following command to generate a .tpr file and got similar error as above: 
`gmx grompp -f SMILES_CCO_10000_using_Interchange.mdp -c SMILES_CCO_10000_using_Interchange.gro -p SMILES_CCO_10000_using_Interchange.top -o SMILES_CCO_10000_using_Interchange.tpr -maxwarn 2`
[10000_CCO.zip](https://github.com/openforcefield/openff-interchange/files/11115712/10000_CCO.zip)

**Comment by mattwthompson** [comment]
Thanks!
