### ISSUE TITLE
Creating a system from IG Amber files: "NonbondedForce: There is already an exception for particles 25 and 41"

### ISSUE THREAD

**Issue by bieniekmateusz** [openforcefield/openff-interchange#676]
Creating an OpenMM system works fine. However, creating Amber files and then loading them with OpenMM runs into an error complaining about nonbonded exceptions were found between the same particles.

Reproduction: 
[omm_exception_part25_41.zip](https://github.com/openforcefield/openff-interchange/files/11311224/omm_exception_part25_41.zip)

**Traceback**
```

File "omm_exception_part25_41/reproduce.py", line 45, in <module>
    parmed.load_file("lig_CHEMBL3265016-1_unconstrained_ig.prm7", "lig_CHEMBL3265016-1_unconstrained_ig.rst7") # parmed.exceptions.AmberError: FLAG ATOM_NAME has 49 elements; expected 48
  File "/mambaforge/envs/qk/lib/python3.9/site-packages/parmed/formats/registry.py", line 196, in load_file
    return cls.parse(filename, *args, **kwargs)
  File "/mambaforge/envs/qk/lib/python3.9/site-packages/parmed/amber/amberformat.py", line 359, in parse
    return LoadParm(filename, *args, **kwargs)
  File "/mambaforge/envs/qk/lib/python3.9/site-packages/parmed/amber/readparm.py", line 67, in LoadParm
    parm = parm.view_as(AmberParm)
  File "/mambaforge/envs/qk/lib/python3.9/site-packages/parmed/amber/amberformat.py", line 426, in view_as
    return cls.from_rawdata(self)
  File "/mambaforge/envs/qk/lib/python3.9/site-packages/parmed/amber/_amberparm.py", line 251, in from_rawdata
    inst.initialize_topology()
  File "/mambaforge/envs/qk/lib/python3.9/site-packages/parmed/amber/_amberparm.py", line 203, in initialize_topology
    self.load_structure()
  File "/mambaforge/envs/qk/lib/python3.9/site-packages/parmed/amber/_amberparm.py", line 499, in load_structure
    self._check_section_lengths()
  File "/mambaforge/envs/qk/lib/python3.9/site-packages/parmed/amber/_amberparm.py", line 1279, in _check_section_lengths
    check_length('ATOM_NAME', natom)
  File "/mambaforge/envs/qk/lib/python3.9/site-packages/parmed/amber/_amberparm.py", line 1276, in check_length
    raise AmberError('FLAG %s has %d elements; expected %d' %
parmed.exceptions.AmberError: FLAG ATOM_NAME has 49 elements; expected 48

Process finished with exit code 1
```

**Software versions**

- Which operating system and version are you using? Arch linux
- How did you install Interchange? Dev, 0.3.1

**Comment by mattwthompson** [comment]
I'll have a look

**Comment by mattwthompson** [comment]
I notice the atom names loaded by the toolkit have padded whitespace. I wonder if this is intentional and if it would be problematic to strip those out. It's causing issues somewhere in mapping the list of strings into the restrictive structure that Amber requires for its Fortran-style parsing.

```python
In [1]: from openff.toolkit import Molecule

In [2]: [
   ...:     atom.name
   ...:     for atom in Molecule.from_file("lig_CHEMBL3265016-1.pdb").to_topology().atoms
   ...: ]
Out[2]:
[' N1 ',
 ' C1 ',
 ' C2 ',
 ' N2 ',
...
```

This is causing problems at some point with text wrapping. I'll fix it anyway, but just dropping whitespace might be easier.

**Comment by bieniekmateusz** [comment]
Ahh I did not notice that. Thanks so much!

**Comment by mattwthompson** [comment]
That will only get you so far, though. The actual problem is that some 1-4 exclusions are double-counted. Through trial-and-error I've found that naphthalene reproduces a similar error, while benzene does not.

```python
 In [8]: ForceField("openff-2.0.0.offxml").create_interchange(
   ...:     Molecule.from_iupac("naphthalene").to_topology()
   ...: ).to_prmtop("x.prmtop")

In [9]: parmed.load_file("x.prmtop")
```

I'm not totally surprised by this bug; my testing involves firing off these files to sander and seeing if they report the same energies as OpenMM. I guess it looks at duplicate 1-4 exclusions and doesn't mind it, whereas both OpenMM and ParmEd parsers are not happy. Writing out multiple exclusions per 1-4 pair is probably the wrong behavior. I'll fix that.

Separately, I'm curious about the use case that requires you to go through Amber files and then back to OpenMM vs. going to OpenMM directly? Not second-guessing your code, just wondering if there's a way Interchange can streamline the process of going from a molecule(s) and force field to simulation.

**Comment by mattwthompson** [comment]
Thanks for the reproduction; I believe I've fixed both of these in the development head. I can run the script you included without errors. I didn't look any deeper than that.

The next release will probably be within a couple of weeks, depending on what other bugs are reported and features I can finish up.

**Comment by bieniekmateusz** [comment]
Hi @mattwthompson , I can save and load the files now and I can reproduce all energy terms but one. The Nonbonded energies (bottom row for IG):
```
--------------  ------------------  ------------------  --------------------  ------------------  ------------------
Name            HarmonicBondForce   HarmonicAngleForce  PeriodicTorsionForce  NonbondedForce      Total Energy
QUBEKit OFFXML  4.97240194233043    112.06718710365426  5.962075505081159     16.131454431635195  139.13311898270103
IG Amber->OMM   4.9724014609325575  112.06719100050545  5.962075539523636     285.7017114200895   408.7033794210512
--------------  ------------------  ------------------  --------------------  ------------------  ------------------
```
I used OpenMM to enumerate the exceptions in nonbonded forces and found some appear to be turned off in the reference but not in the  IG Amber files. 

I am happy to make a new issue for it, the script `nonbonded` is a bit messy:
[omm_exception_part25_41_nb.zip](https://github.com/openforcefield/openff-interchange/files/11330756/omm_exception_part25_41_nb.zip)

**Comment by mattwthompson** [comment]
Please do - copying and pasting the same tarball is okay, don't need a long write-up. From a quick glance at the files I'm not sure if it's an issue with how the energies are evaluated or if Interchange is writing something incorrectly. I'll have a look later.
