### ISSUE TITLE
Missing v-site exceptions

### ISSUE THREAD

**Issue by jthorton** [openforcefield/openff-interchange#905]
**Description**

When creating an openmm system containing a molecule with multiple v-sites exceptions between the v-sites seem to be missing along with scaled 1-4 interactions between v-sites which make up a torsion. 

**Reproduction**

Attached is a force field which uses v-sites to move the LJ centre away from the hydrogen atom, you can see from the openmm system that v-site v-site interactions are missing. You can also find the missing 1-4 interactions when using methanol as the example molecule.
```python
import openmm
from openff.toolkit import Molecule, ForceField
from openff.interchange import Interchange
from openff.units import unit

water = Molecule.from_smiles('O')
water.generate_conformers()

ff = ForceField('off_site.offxml')

interchange = Interchange.from_smirnoff(force_field=ff, topology=water.to_topology())

system = interchange.to_openmm_system()
with open('water_system.xml', 'w') as out:
    out.write(openmm.XmlSerializer.serialize(system))
```

**Output**

Please include the output, including full tracebacks of any errors, resulting from the reproduction.

**Software versions**

- Which operating system and version are you using? Confirmed on Linux and macos
- How did you install Interchange? `mamba install openff-interchange`
- What is the output of running `conda list`?
```
# packages in environment at /home/josh/mambaforge/envs/openmm_8:
#
# Name                    Version                   Build  Channel
openff-amber-ff-ports     0.0.4              pyhca7485f_0    conda-forge
openff-forcefields        2024.01.0          pyhca7485f_0    conda-forge
openff-interchange        0.3.20             pyhd8ed1ab_0    conda-forge
openff-interchange-base   0.3.20             pyhd8ed1ab_0    conda-forge
openff-models             0.1.2              pyhca7485f_0    conda-forge
openff-toolkit            0.15.2             pyhd8ed1ab_0    conda-forge
openff-toolkit-base       0.15.2             pyhd8ed1ab_0    conda-forge
openff-units              0.2.1              pyh1a96a4e_0    conda-forge
openff-utilities          0.1.12             pyhd8ed1ab_0    conda-forge
```
[off_site.txt](https://github.com/openforcefield/openff-interchange/files/14334230/off_site.txt)

**Comment by mattwthompson** [comment]
Nice find, I can reproduce this and understand the difference between expected and observed behavior. Something is going awry in this mess of logic:

https://github.com/openforcefield/openff-interchange/blob/f69816c2fac3c5b506392fcec85c95be5b1f1a16/openff/interchange/interop/openmm/_nonbonded.py#L488-L578

I'll drop in a debugger later

**Comment by mattwthompson** [comment]
Wow! I was hoping you found an esoteric case to throw at me and this hellish logic was just a typo or something, but this is a much deeper issue. From my parsing of this tangled knot of logic, exceptions between virtual sites (i.e. neither particle is massive) were never added. I have the water case working now, I think:

```
$ python issue-905.py
Adding parent-(child of neighbor) exceptions of parent p1=0 or p2=1
	excluding p1=0, virtual_particle_of_p2=3
Adding (child of this parent)-(child of neighbor) exceptions of parent p1=0 or p2=1
Adding parent-(child of neighbor) exceptions of parent p1=0 or p2=2
	excluding p1=0, virtual_particle_of_p2=4
Adding (child of this parent)-(child of neighbor) exceptions of parent p1=0 or p2=2
Adding parent-(child of neighbor) exceptions of parent p1=1 or p2=2
	excluding virtual_particle_of_p1=3 p2=2
	excluding p1=1, virtual_particle_of_p2=4
Adding (child of this parent)-(child of neighbor) exceptions of parent p1=1 or p2=2
	excluding v1=3, v2=4
Adding parent-child exceptions for each parent with virtual sites
	excluding parent=1, virtual_particle=3
	excluding parent=2, virtual_particle=4
```
```
			<Exceptions>
				<Exception eps="0" p1="0" p2="1" q="0" sig="1"/>
				<Exception eps="0" p1="0" p2="2" q="0" sig="1"/>
				<Exception eps="0" p1="1" p2="2" q="0" sig="1"/>
				<Exception eps="0" p1="3" p2="0" q="0" sig="1"/>
				<Exception eps="0" p1="4" p2="0" q="0" sig="1"/>
				<Exception eps="0" p1="3" p2="2" q="0" sig="1"/>
				<Exception eps="0" p1="4" p2="1" q="0" sig="1"/>
				<Exception eps="0" p1="3" p2="4" q="0" sig="1"/>  <-- Here's the new one!
				<Exception eps="0" p1="1" p2="3" q="0" sig="1"/>
				<Exception eps="0" p1="2" p2="4" q="0" sig="1"/>
			</Exceptions>
```

Coming back to this shortly to get the 1-4 behaviors in line, then I think this warrants a quick release.

**Comment by djcole56** [comment]
Thanks! I think it would not have a big effect on vsites that share the same parent, which is probably the most common / only use case until now. It's only when we had vsites all over the molecule that they start doing odd things. But agreed it's worth a release.

**Comment by mattwthompson** [comment]
I think with #906 the main behavior changes are what were reported here, namely some combination of

* Virtual site-virtual site interactions are excluded when parents are (non-)interacting as 1-2 or 1-3 intramolecular pairs
* Virtual site-virtual site interactions are scaled when parents are 1-4 interacting
* Virtual site-atom interactions are scaled when the virtual site's parent and the other atom are 1-4 interacting


I'm not sure how much I trust the previous logic past
* Excluding the interactions
  * between a virtual site and its parent
  * between virtual sites sharing the same parent
  * between a virtual site and its parent's nearest (atomic) neighbors

The only change I made to this reproduction is adding charge increments to the off-site hydrogens, just to ensure the 1-4 electrostatics (like any of the hydrogen-hydrogen pairs in methanol) are accurately calculated.

The logic to handle all of these cases will never be compact but I've also refactored the code to be slightly more readable so that when I or somebody else comes to back to it there is, I hope, less time spend trying to understand what's going on. (Or, for that matter, if scientists want to experiment with [a new exclusion policy](https://github.com/openforcefield/openff-toolkit/blob/0.10.0/openff/toolkit/typing/engines/smirnoff/parameters.py#L4687-L4710).) I'm fairly confident all of the ways virtual sites and atoms can interact (intramolecular-ly) are covered by tests now, at least for `exclusion_policy="parents"`.

How exactly these missing cases weren't causing more issues, I'm not exactly sure. Four-and five-site water models are fine, but most (?) ligand chemistries should be incorrect. I checked in with @lilyminium and verified her current experiments are NOT using this code path, though some benchmarking code might.

I'm going to do some final checks on the linked PR and, if it doesn't break something in the ecosystem prior to today's workshop, ship it out.
