### ISSUE TITLE
How to check missing parameters before create_interchange?

### ISSUE THREAD

**Issue by hodakamori** [openforcefield/openff-interchange#913]
**Description**
Thanks for a great tool, very helpful for MD simulations in OpenMM!

In my application, I often use atoms that have no parameters registerd in OpenFF (like ``openff-2.0.0.offxml``).
If I try to create an interchange in this situation, an error is thrown.
For example, when I use an iodine molecule as follows,

```python
from openff.toolkit import ForceField, Molecule
smiles = "II"
mol = Molecule.from_smiles(smiles)
force_field = ForceField("openff-2.0.0.offxml")
topology = ligand.to_topology()
system = force_field.create_openmm_system(
    topology,
    charge_from_molecules=[mol],
    )
```
I got an error like this.

```
UnassignedBondError: BondHandler was not able to find parameters for the following valence terms:

- Topology indices (0, 1): names and elements ( I), ( I), 
```

This error itself is normal, but I would like to know in advance if the parameter for the molecule are available before assigning parameters, and if not, which parameters are missing.

I tried to check the parameters that are actually assigned as follows,

```python
ff_applied_parameters = force_field.label_molecules(topology)
for mol_idx, mol_forces in enumerate(ff_applied_parameters):
    print(f"Forces for molecule {mol_idx}")
    for force_tag, force_dict in mol_forces.items():
        print(f"\n{force_tag}:")
        for atom_indices, parameter in force_dict.items():
            atomstr = ""
            for idx in atom_indices:
                atomstr += "%3s" % idx
            print(
                f"atoms: {atomstr}  parameter_id: {parameter.id}  smirks {parameter.smirks}"
            )
```
but if there is a parameter that cannot be assigned, that parameter seems to be set to empty.
In fact, for the iodine-iodine bond, the topology exists, but the parameter does not exist.
Is there any way to check in advance which parameters are missing for the topology?

```
Forces for molecule 0

Constraints:

Bonds:

Angles:

ProperTorsions:

ImproperTorsions:

vdW:
atoms:   0  parameter_id: n26  smirks [#53:1]
atoms:   1  parameter_id: n26  smirks [#53:1]

Electrostatics:

LibraryCharges:

ToolkitAM1BCC:
```

**Comment by mattwthompson** [comment]
You've pretty much found the API points that I would recommend[^1]; under the hood, `ForceField.label_molecules` pretty much does the same stuff as creating an `Interchange` object (namely filling out the the collection classes). This can be simple or tricky depending on the level of granularity you're after

* Rough pass: just see if the element(s) are [in the force field at all](https://github.com/choderalab/espaloma/issues/206#issuecomment-1936582255)
* Slightly more detailed pass: wrap your second code block into a function and error out in some particular cases`
  * This doesn't work for all parameter handlers; for example, throwing an error if `len(matches['Bonds']) < topology.n_bonds` is probably good, but the same logic for improper torsions would not work.
  * The logic within Interchange is around [here](https://github.com/openforcefield/openff-interchange/blob/v0.3.21/openff/interchange/smirnoff/_base.py#L103)
* Depending on the application, it might be easiest to just go Grace Hopper style and ask for forgiveness instead of permission

```python
try:
    force_field.create_interchange(...)
# there are a few different exceptions that can be thrown here - this base class captures if bond/angle/torsion parameters are missing
except (UnassignedValenceParameterException, ...):
    # deal with it here - log, re-raise exception, etc.
```

In the case of molecular iodine, it seems like the thrown error is pretty much getting what you're asking for. Are there other cases that are tricker to deal with?

[^1]: I planned to point you to [this](https://docs.openforcefield.org/en/latest/examples/openforcefield/openff-toolkit/inspect_assigned_parameters/inspect_assigned_parameters.html) example, but it looks like you've already come across it

**Comment by hodakamori** [comment]
Thank you for your response.
In my case, the ERROR catch looks good!
