### ISSUE TITLE
`Interchange.from_openmm` should raise an exception if the topology doesn't match the system

### ISSUE THREAD

**Issue by Yoshanuikabundi** [openforcefield/openff-interchange#921]
**Description**
I'm not sure how detailed this check /c|sh|w/ould be, but raising an exception if the Topology and System have different numbers of atoms would have saved me an hour or so last night - I had a lot of cryptic errors that all stemmed back to changing a variable name and accidentally still using the old name in one place. I imagine virtual sites might make this a pain.

Passing OpenFF topologies to `from_openmm` is otherwise a great experience! And this change would probably be useful for taking OpenMM topologies as well.

**Comment by mattwthompson** [comment]
> I imagine virtual sites might make this a pain.

Your imagination is correct - but that's implicitly unsupported right now so it's worthwhile to make it explicitly unsupported.

How stringent a check are we talking here? The most naive check that comes to mind is checking that the number of particles in the system matches the number of atoms in the topology. (This could be massaged slightly to only consider massive particles, since virtual sites don't exist in OpenFF's topologies.) I imagine that should cover most cases of accidentally passing in the wrong variables.

I think connectivity checks would be trickier to implement (rigid water often doesn't have bonds in OpenMM models, for example) and risk some false negatives, so I don't think I'd go for that in the first pass here.

**Comment by Yoshanuikabundi** [comment]
> How stringent a check are we talking here? The most naive check that comes to mind is checking that the number of particles in the system matches the number of atoms in the topology. (This could be massaged slightly to only consider massive particles, since virtual sites don't exist in OpenFF's topologies.) I imagine that should cover most cases of accidentally passing in the wrong variables.

That sounds great. `openmm.System` seems to have a `isVirtualSite(index)` method, which might be preferable to checking mass because OpenMM's recommended way to freeze atoms is to set their mass to zero.

I agree connectivity has all sorts of bugbears that are likely to get worse in the future!
