### ISSUE TITLE
units for `Interchange.collection['Bonds'].get_system_parameters()`

### ISSUE THREAD

**Issue by dominicrufa** [openforcefield/openff-interchange#944]
Hi team,
I am querying system parameters for bonds, angles, proper, and improper torsions (as well as charges and lj params, though i am not there yet). what is the convention/docs for the units of these `SMIRNOFFCollection` objects' `get_system_parameters` attrs? they don't appear to be the `openmm.unit.md_unit_system` convention

Thanks.

**Comment by mattwthompson** [comment]
These are Pint-styled units from https://github.com/openforcefield/openff-units

I don't think I can make guarantees right now, but this is something to check. (This is the only part of the codebase that is sloppy with units, since I wasn't able to get JAX to understand them). Until then, the units are inspectable, albeit a little tucked away, in the API. In this case the units appear to match what's in the SMIRNOFF force field (AKMA-ish), if you're using a different source this might not be true:

```python
In [22]: {
    ...:     parameter.units
    ...:     for potential in out["Bonds"].potentials.values()
    ...:     for parameter in potential.parameters.values()
    ...: }
Out[22]: {<Unit('angstrom')>, <Unit('kilocalorie / angstrom ** 2 / mole')>}

In [23]: sage['Bonds'].parameters[-1]
Out[23]: <BondType with smirks: [#8:1]-[#1:2]  id: b88  length: 0.9716763312559 angstrom  k: 1087.053566377 kilocalorie / angstrom ** 2 / mole  >

**Comment by dominicrufa** [comment]
i hadn't read through this thoroughly: https://docs.openforcefield.org/projects/interchange/en/stable/using/collections.html. apologies, but thank you for the clarification!
